pipeline:
  loader:
    name: LuxonisLoader
    params:
      dataset_name: quickstartcoco
      view: [val]

  engine:
    name: onnx
    model_path: examples/quickstart/yolov6.onnx.tar

  evaluators:
    - task_name: ""
      # The YOLOv6 parser and its parameters are read from the NNArchive.
      metrics:
        - name: BboxMeanAveragePrecision
          params:
            iou_type: bbox
      visualizers:
        - name: BBoxVisualizer
          display: false
          save: true
          save_dir: visualizations/quickstart/onnx
